/* test_toi_4.mac */

(assume(ap>0),0);
0;

/* Trivial for testing */
table_integrate(x,x,0,1);
1/2;
table_integrate(x,x,0,2);
2;
table_integrate(x,x,0,3);
false;
table_integrate(x^2,x,0,1);
1/3;
table_integrate(sin(u)^2,u,0,%pi);
%pi/2;
table_integrate(sin(u)^2,u,0,%pi/2);
%pi/4;
table_integrate(sin(u)^2,u,0,2*%pi);
false;


/* Non-trivial that maxima cannot solve */

/* CRC 603 */
table_integrate(tan(x)/x,x,0,inf);
%pi/2;

/* CRC 604 */
table_integrate(tan(ap*x)/x,x,0,inf);
%pi/2;

/* CRC 622 */
table_integrate(sin(x)^3/x^2,x,0,inf);
3*log(3)/4;

/* DLMF 9.11.16 */
table_integrate(airy_ai(x)^3,x,minf,inf);
gamma(1/3)^2/(4*%pi^2);

/* DLMF 9.11.17 */
table_integrate(airy_ai(x)^4,x,0,inf);
log(3)/(24*%pi^2);

/* DLMF 9.11.18 */
table_integrate(airy_ai(x)^4,x,0,inf);
log(3)/(24*%pi^2);

/* not defined */
table_integrate(airy_ai(x)^4,x,0,1);
false;

/* not defined */
table_integrate(2*airy_ai(x)^4,x,0,inf);
false;

/* not defined */
table_integrate(airy_ai(x+1)^4,x,0,inf);
false;

(forget(ap>0),0);
0;
