(load("toi_testing.mac"),0);
0;

/* Some of the Jacobi elliptic functions are recursive,
   and return with calls to integrate unevaluated.

   A short term fix.
   
   Borrowing from share/contrib/integration/abs_integrate.mac
*/

(matchdeclare(x, symbolp, [q], lambda([s], true)),
block([simp:false],tellsimpafter('integrate(q,x),table_integrate(q,x))),
0);
0;

/* Check jacobi integrals. Can't reliably simplify to zero
   Just check that diff(integral,u)-integrand is small at a random point
   This take a few seconds extra */
(check_jacobi(integrand,u):=block(
   [integral,r,thresh:1.0e-13],
   integral:table_integrate(integrand,u),
   /* FIXME: This is a work around */
   integral:ev(integral,infeval),
   r:diff(integral,u)-integrand,
   r1:block([keepfloat:true],subst([u=0.47,m=0.9],r)),
   if (abs(r1)<thresh) then
     integral
   else
     [integral,r1]), 0);
0;

/*  G&R 5.13: Jacobian elliptic functions */

/* G&R 5.131.1 */
check_jacobi(jacobi_sn(u,m)^3,u);
(((3*(m+1)-2*m-2)*log(jacobi_dn(u,m)-sqrt(m)*jacobi_cn(u,m)))/sqrt(m)
 +jacobi_cn(u,m)*jacobi_dn(u,m))/(2*m);
check_jacobi(jacobi_sn(u,m)^4,u);
(((4*(m+1)-2*m-2)*(u-elliptic_e(asin(jacobi_sn(u,m)),m)))/m
 +jacobi_cn(u,m)*jacobi_dn(u,m)*jacobi_sn(u,m)-u)/(3*m);
check_jacobi(jacobi_sn(u,m)^5,u);
(((5*(m+1)-2*m-2)*(((3*(m+1)-2*m-2)
                         *log(jacobi_dn(u,m)-sqrt(m)*jacobi_cn(u,m)))
                         /sqrt(m)
                         +jacobi_cn(u,m)*jacobi_dn(u,m)))
 /(2*m)
 -(2*log(jacobi_dn(u,m)-sqrt(m)*jacobi_cn(u,m)))/sqrt(m)
 +jacobi_cn(u,m)*jacobi_dn(u,m)*jacobi_sn(u,m)^2)
 /(4*m);
check_jacobi(jacobi_sn(u,m)^6,u);
 ((-(3*(u-elliptic_e(asin(jacobi_sn(u,m)),m)))/m)
 +((6*(m+1)-2*m-2)*(((4*(m+1)-2*m-2)*(u-elliptic_e(asin(jacobi_sn(u,m)),m)))/m
                   +jacobi_cn(u,m)*jacobi_dn(u,m)*jacobi_sn(u,m)-u))
  /(3*m)+jacobi_cn(u,m)*jacobi_dn(u,m)*jacobi_sn(u,m)^3)
 /(5*m);

check_jacobi(jacobi_sn(u,m)^-2,u);
(-elliptic_e(asin(jacobi_sn(u,m)),m))
 -(jacobi_cn(u,m)*jacobi_dn(u,m))/jacobi_sn(u,m)+u;
check_jacobi(jacobi_sn(u,m)^-3,u);
-((((-m)-1)*log((jacobi_dn(u,m)-jacobi_cn(u,m))/jacobi_sn(u,m))
 +(jacobi_cn(u,m)*jacobi_dn(u,m))/jacobi_sn(u,m)^2)/2);

/* G&R 5.131.2 */
check_jacobi(jacobi_cn(u,m)^3,u);
(((3*m+3*(1-m)-3)*log((sqrt(1-m)*jacobi_sn(u,m)+jacobi_dn(u,m))
                             /jacobi_cn(u,m)))
 /sqrt(1-m)
 +((3*(2*m-1)-4*m+2)*acos(jacobi_dn(u,m)))/sqrt(m)
 +jacobi_dn(u,m)*jacobi_sn(u,m))
 /(2*m);

check_jacobi(jacobi_cn(u,m)^4,u);
(((4*(2*m-1)-4*m+2)*(elliptic_e(asin(jacobi_sn(u,m)),m)-(1-m)*u))/m
 +jacobi_cn(u,m)*jacobi_dn(u,m)*jacobi_sn(u,m)+(3*m+4*(1-m)-3)*u)
 /(3*m);

check_jacobi(jacobi_cn(u,m)^-2,u);
-((elliptic_e(asin(jacobi_sn(u,m)),m)
 -(jacobi_dn(u,m)*jacobi_sn(u,m))/jacobi_cn(u,m)-((1-m)*u))/(1-m));

/* G&R 5.131.3 */ 
check_jacobi(jacobi_dn(u,m)^3,u);
((2-m)*asin(jacobi_sn(u,m))+m*jacobi_cn(u,m)*jacobi_sn(u,m))/2;

check_jacobi(jacobi_dn(u,m)^4,u);
 ((4-2*m)*elliptic_e(asin(jacobi_sn(u,m)),m)
 +m*jacobi_cn(u,m)*jacobi_dn(u,m)*jacobi_sn(u,m)+(m-1)*u)
 /3;

check_jacobi(jacobi_dn(u,m)^-2,u);
(elliptic_e(asin(jacobi_sn(u,m)),m)
 -(m*jacobi_cn(u,m)*jacobi_sn(u,m))/jacobi_dn(u,m))/(1-m);

check_jacobi(jacobi_dn(u,m)^-3,u);
(((2-m)*acos(jacobi_cn(u,m)/jacobi_dn(u,m)))/sqrt(1-m)
 -(m*jacobi_cn(u,m)*jacobi_sn(u,m))/jacobi_dn(u,m)^2)/(2-2*m);

/* G&R 5.132.1 */
check_jacobi(1/jacobi_sn(u,m),u);
log((jacobi_dn(u,m)-jacobi_cn(u,m))/jacobi_sn(u,m));

/* G&R 5.132.2 */
check_jacobi(1/jacobi_cn(u,m),u);
log((sqrt(1-m)*jacobi_sn(u,m)+jacobi_dn(u,m))/jacobi_cn(u,m))/sqrt(1-m);

/* G&R 5.132.3 */
check_jacobi(1/jacobi_dn(u,m),u);
acos(jacobi_cn(u,m)/jacobi_dn(u,m))/sqrt(1-m);

/* G&R 5.134.1 */
check_jacobi(jacobi_sn(u,m)^2,u);
(u-elliptic_e(asin(jacobi_sn(u,m)),m))/m;

/* G&R 5.134.2 */
check_jacobi(jacobi_cn(u,m)^2,u);
(elliptic_e(asin(jacobi_sn(u,m)),m)-(1-m)*u)/m;

/* G&R 5.134.3 */
check_jacobi(jacobi_dn(u,m)^2,u);
elliptic_e(asin(jacobi_sn(u,m)),m);

/* G&R 5.135.1 */
check_jacobi(jacobi_sn(u,m)/jacobi_cn(u,m),u);
log((jacobi_dn(u,m)+sqrt(1-m))/jacobi_cn(u,m))/sqrt(1-m);

/* G&R 5.135.2 */
check_jacobi(jacobi_sn(u,m)/jacobi_dn(u,m),u);
acot((sqrt(m)*jacobi_cn(u,m))/sqrt(1-m))/(sqrt(1-m)*sqrt(m));

/* G&R 5.135.3 */
check_jacobi(jacobi_cn(u,m)/jacobi_sn(u,m),u);
log((1-jacobi_dn(u,m))/jacobi_sn(u,m));

/* G&R 5.135.4 */
check_jacobi(jacobi_cn(u,m)/jacobi_dn(u,m),u);
-log((1-sqrt(m)*jacobi_sn(u,m))/jacobi_dn(u,m))/sqrt(m);

/* G&R 5.135.5 */
check_jacobi(jacobi_dn(u,m)/jacobi_cn(u,m),u);
log((1+jacobi_sn(u,m))/jacobi_cn(u,m));

/* G&R 5.135.6 */
check_jacobi(jacobi_dn(u,m)/jacobi_sn(u,m),u);
log((1-jacobi_cn(u,m))/(1+jacobi_cn(u,m)))/2;

/* G&R 5.136.1 */
check_jacobi(jacobi_sn(u,m)*jacobi_cn(u,m),u);
-(jacobi_dn(u,m)/m);

/* G&R 5.136.2 */
check_jacobi(jacobi_sn(u,m)*jacobi_dn(u,m),u);
-jacobi_cn(u,m);

/* G&R 5.136.3 */
check_jacobi(jacobi_cn(u,m)*jacobi_dn(u,m),u);
jacobi_sn(u,m);

/* G&R 5.137.1 */
check_jacobi(jacobi_sn(u,m)/jacobi_cn(u,m)^2,u);
(1/(1-m))*jacobi_dn(u,m)/jacobi_cn(u,m);

/* G&R 5.137.2 */
check_jacobi(jacobi_sn(u,m)/jacobi_dn(u,m)^2,u);
-((1/(1-m))*jacobi_cn(u,m)/jacobi_dn(u,m));

/* G&R 5.137.3 */
check_jacobi(jacobi_cn(u,m)/jacobi_sn(u,m)^2,u);
-(jacobi_dn(u,m)/jacobi_sn(u,m));

/* G&R 5.137.4 */
check_jacobi(jacobi_cn(u,m)/jacobi_dn(u,m)^2,u);
jacobi_sn(u,m)/jacobi_dn(u,m);

/* G&R 5.137.5 */
check_jacobi(jacobi_dn(u,m)/jacobi_sn(u,m)^2,u);
-(jacobi_cn(u,m)/jacobi_sn(u,m));

/* G&R 5.137.6 */
check_jacobi(jacobi_dn(u,m)/jacobi_cn(u,m)^2,u);
jacobi_sn(u,m)/jacobi_cn(u,m);

/* G&R 5.138.1 */
check_jacobi(jacobi_cn(u,m)/(jacobi_sn(u,m)*jacobi_dn(u,m)),u);
log(jacobi_sn(u,m)/jacobi_dn(u,m));

/* G&R 5.138.2 */
check_jacobi(jacobi_sn(u,m)/(jacobi_cn(u,m)*jacobi_dn(u,m)),u);
log(jacobi_dn(u,m)/jacobi_cn(u,m))/(1-m);

/* G&R 5.138.3 */
check_jacobi(jacobi_dn(u,m)/(jacobi_sn(u,m)*jacobi_cn(u,m)),u);
log(jacobi_sn(u,m)/jacobi_cn(u,m));

/* G&R 5.139.1 */
check_jacobi(jacobi_cn(u,m)*jacobi_dn(u,m)/jacobi_sn(u,m),u);
log(jacobi_sn(u,m));

/* G&R 5.139.2 */
check_jacobi(jacobi_sn(u,m)*jacobi_dn(u,m)/jacobi_cn(u,m),u);
-log(jacobi_cn(u,m));

/* G&R 5.139.2 */
check_jacobi(jacobi_sn(u,m)*jacobi_cn(u,m)/jacobi_dn(u,m),u);
-(log(jacobi_dn(u,m))/m);

/* G&R 5.3: The Sine Integral and the Cosine Integral */

/* G&R 5.31.1 */
check_toi(cos(a*y)*expintegral_ci(b*y),y);
sin(a*y)*expintegral_ci(b*y)/a-(expintegral_si((a+b)*y)+expintegral_si((a-b)*y))/(2*a);
check_toi(cos(2*y)*expintegral_ci(3*y),y);
(sin(2*y)*expintegral_ci(3*y))/2-(expintegral_si(5*y)-expintegral_si(y))/4;

/* G&R 5.31.2 */
check_toi(sin(a*x)*expintegral_ci(b*x),x,notequal(a,b));
-cos(a*x)*expintegral_ci(b*x)/a+(expintegral_ci((a+b)*x)+expintegral_ci((a-b)*x))/(2*a);

/* G&R 5.32.1 */
check_toi(cos(x)*expintegral_si(5*x),x);
(expintegral_ci(6*x)-expintegral_ci((-4)*x))/2+sin(x)*expintegral_si(5*x);

/* G&R 5.32.2 */
check_toi(expintegral_si(x)*sin(2*x),x);
(expintegral_si(3*x)-expintegral_si(x))/4-(expintegral_si(x)*cos(2*x))/2;

/* G&R 5.33.1 */
check_toi(expintegral_ci(a*x)*expintegral_ci(b*x),x);
x*expintegral_ci(a*x)*expintegral_ci(b*x)
 +(expintegral_si((a+b)*x)+expintegral_si((a-b)*x))/(2*a)
 +(expintegral_si((a+b)*x)+expintegral_si((b-a)*x))/(2*b)
 -(sin(a*x)*expintegral_ci(b*x)/a)-(sin(b*x)*expintegral_ci(a*x)/b);

check_toi(expintegral_ci(a*x)^2,x);
(a*x*expintegral_ci(a*x)^2-2*sin(a*x)*expintegral_ci(a*x)
 +expintegral_si(2*a*x))/a;

/* G&R 5.33.2 */
check_toi(expintegral_si(a*x)*expintegral_si(b*x),x);
x*expintegral_si(a*x)*expintegral_si(b*x)
 -((expintegral_si((a+b)*x)+expintegral_si((a-b)*x))/(2*b))
 -((expintegral_si((a+b)*x)+expintegral_si((b-a)*x))/(2*a))
 +cos(a*x)*expintegral_si(b*x)/a+cos(b*x)*expintegral_si(a*x)/b;

check_toi(expintegral_si(a*x)^2,x);
(2*cos(a*x)*expintegral_si(a*x)
 +a*x*expintegral_si(a*x)^2-expintegral_si(2*a*x))/a;

/* G&R 5.33.3 */
check_toi(expintegral_si(a*x)*expintegral_ci(b*x),x,notequal(a,b));
x*expintegral_si(a*x)*expintegral_ci(b*x)
 +(cos(a*x)*expintegral_ci(b*x)/a)-(sin(b*x)*expintegral_si(a*x)/b)
 -((1/(2*a)+1/(2*b))*expintegral_ci((a+b)*x))
 -((1/(2*a)-1/(2*b))*expintegral_ci((a-b)*x));

/* functions.wolfram.com/06.37.21.0006.01 */
check_toi(x*expintegral_si(a*x),x);
(a^2*expintegral_si(a*x)*x^2+a*cos(a*x)*x-sin(a*x))/(2*a^2);

/* functions.wolfram.com/06.37.21.0008.01 */
check_toi(expintegral_si(z)/z^2,z);
(-sin(z)-expintegral_si(z)+z*expintegral_ci(z))/z;

/* functions.wolfram.com/06.37.21.0021.01 */
check_toi(sin(%pi*x)*expintegral_si(%pi*x),x);
expintegral_si(2*%pi*x)/(2*%pi)-(cos(%pi*x)*expintegral_si(%pi*x)/%pi);

/* functions.wolfram.com/06.37.21.0023.01 */
/* %phi is just a test of maxima constants  */
check_toi(cos(%phi*x)*expintegral_si(%phi*x),x);
 (expintegral_ci(2*%phi*x)+2*expintegral_si(%phi*x)*sin(%phi*x)
   -log(%phi*x))/(2*%phi);

/* functions.wolfram.com/06.38.21.0006.01 */
check_toi(x*expintegral_ci(a*x),x);
-((a*x*sin(a*x)-a^2*x^2*expintegral_ci(a*x)+cos(a*x))/(2*a^2));

/* functions.wolfram.com/06.38.21.0008.01 */
check_toi(expintegral_ci(4*z)/z^2,z);
((-4*z*expintegral_si(4*z))-expintegral_ci(4*z)-cos(4*z))/z;

/* functions.wolfram.com/06.38.21.0021.01 */
check_toi(sin(a*x)*expintegral_ci(a*x),x);
(expintegral_ci(2*a*x)+log(a*x)-2*cos(a*x)*expintegral_ci(a*x))/(2*a);

/* functions.wolfram.com/06.38.21.0023.01 */
check_toi(cos(a*x)*expintegral_ci(a*x),x);
sin(a*x)*expintegral_ci(a*x)/a-(expintegral_si(2*a*x)/(2*a));

